# Generated by Django 3.1.3 on 2020-12-30 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainWebApp', '0002_healthguarddoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReportDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(choices=[('general', 'General'), ('very_high', 'Very High'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=55, verbose_name='disease type')),
                ('seriousness_type', models.CharField(max_length=15, verbose_name='seriousness type')),
                ('description', models.CharField(max_length=700, verbose_name='description')),
            ],
            options={
                'db_table': 'TestReportDescription',
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='test ID')),
                ('type', models.CharField(choices=[('general', 'General'), ('dengue', 'Dengue'), ('chikungunya', 'Chikungunya')], max_length=55, verbose_name='test type')),
                ('symptoms', models.CharField(max_length=500, verbose_name='symptoms')),
                ('result', models.CharField(max_length=300, verbose_name='result')),
                ('days', models.IntegerField(verbose_name='days')),
                ('chances', models.IntegerField(verbose_name='chances')),
                ('is_open_for_verification', models.BooleanField(default=False, verbose_name='is_open_for_verification')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date of Test')),
                ('doctor_description', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='description by doctor')),
                ('desc', models.ForeignKey(default='Not Identified', on_delete=django.db.models.deletion.CASCADE, to='DiseasePrediction.testreportdescription', verbose_name='Description Table Id')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainWebApp.healthguarddoctor', verbose_name='verifier doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'TestReports',
            },
        ),
    ]
