# Generated by Django 3.1.3 on 2020-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseasePrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreportdescription',
            name='disease',
            field=models.CharField(choices=[('general', 'General'), ('dengue', 'Dengue'), ('chikungunya', 'Chikungunya')], max_length=55, verbose_name='disease type'),
        ),
        migrations.AlterField(
            model_name='testreportdescription',
            name='seriousness_type',
            field=models.CharField(choices=[('general', 'General'), ('very_high', 'Very High'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=15, verbose_name='seriousness type'),
        ),
    ]
