# Generated by Django 3.1.3 on 2021-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiseasePrediction', '0003_auto_20201230_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('dengue', 'Dengue'), ('chikungunya', 'Chikungunya'), ('malaria', 'Malaria'), ('covid', 'Covid')], max_length=55, verbose_name='test type'),
        ),
    ]
