# Generated by Django 3.1.3 on 2020-12-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGuardDoctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MainWebApp.healthguarduser', verbose_name='user')),
                ('qualification', models.CharField(max_length=20, verbose_name='qualification')),
                ('speciality', models.CharField(max_length=255, verbose_name='speciality')),
                ('license_pdf', models.FileField(upload_to='license/%Y/%m/', verbose_name='license_pdf')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is_approved')),
            ],
            options={
                'db_table': 'Doctors',
            },
        ),
    ]
