# Generated by Django 3.1.3 on 2021-02-23 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainWebApp', '0002_healthguarddoctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppointmentPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_points', models.IntegerField(default=2, verbose_name='Appointment points')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'UserAppointmentPoints',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=500, verbose_name='Clinic address')),
                ('city', models.TextField(max_length=100, verbose_name='Clinic City')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainWebApp.healthguarddoctor', verbose_name='Clinic Doctor')),
            ],
            options={
                'db_table': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('appointment_date_time', models.DateTimeField(verbose_name='Appointment DateTime')),
                ('appointment_status', models.TextField(default='pending', verbose_name='Current Status')),
                ('appointment_approval', models.BooleanField(default=False, verbose_name='Appointment Approval')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.clinic', verbose_name='Clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'Appointments',
            },
        ),
    ]
