# Generated by Django 3.1.3 on 2021-02-23 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='UserAppointmentPoints',
            new_name='UserAppointmentPoint',
        ),
    ]
